---
name: Solaris-SysInfo
version: 0.03
author:
  - 'Paul Evans E<lt>leonerd@leonerd.org.ukE<gt>'
abstract: A perl wrapper around Solaris' sysinfo(1) system call
license: perl
build_requires:
  Test::More: 0
provides:
  Solaris::SysInfo:
    file: lib/Solaris/SysInfo.pm
    version: 0.03
generated_by: Module::Build version 0.26
